- name: Debug message 1
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars: 
    array:
    - Jimmy
    - Johnny
  tasks:
  - name: Debug msg
    debug:
      msg: "{{ array[1] }}"