- name: Serial Keyword
  hosts: all
  serial: # 1 machine for 1st batch, 3 machines for 2nd batch, 5 machines for 3rd batch
  - 1
  - 3
  - 5
  tasks:
  - name: 1st Task
    command: "echo 1"
  - name: 2nd Task
    command: "echo 2"