- name: Create new users and uid with loop
  hosts: nodes
  become_user: root
  become_method: sudo
  become: true
  tasks:
    - name: Create  new users
      user:
        name: '{{ item.name }}'
        uid: '{{ item.uid }}'
        state: present
      loop:
        - name: kimi
          uid: 1020
        - name: schumi
          uid: 1030
        - name: verstappen
          uid: 1040
