- name: Create new users with loop
  hosts: nodes
  become_user: root
  become_method: sudo
  become: true
  tasks:
    - name: Create  new users
      user:
        name: '{{ item }}'
        state: present
      with_items:
        - kimi
        - schumi
        - verstappen
